/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SidebarImport } from './routes/_sidebar'
import { Route as IndexImport } from './routes/index'
import { Route as SidebarPoliciesImport } from './routes/_sidebar/policies'
import { Route as SidebarAnalyticsImport } from './routes/_sidebar/analytics'
import { Route as SidebarClustersIndexImport } from './routes/_sidebar/clusters/index'
import { Route as SidebarClustersClusterIdImport } from './routes/_sidebar/clusters/$clusterId'

// Create Virtual Routes

const SidebarClustersRoute = createFileRoute('/_sidebar/clusters')()

// Create/Update Routes

const SidebarRoute = SidebarImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SidebarPoliciesRoute = SidebarPoliciesImport.update({
  path: '/policies',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarAnalyticsRoute = SidebarAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarClustersIndexRoute = SidebarClustersIndexImport.update({
  path: '/clusters/',
  getParentRoute: () => SidebarRoute,
} as any)

const SidebarClustersClusterIdRoute = SidebarClustersClusterIdImport.update({
  path: '/clusters/$clusterId',
  getParentRoute: () => SidebarRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SidebarImport
      parentRoute: typeof rootRoute
    }
    '/_sidebar/analytics': {
      id: '/_sidebar/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof SidebarAnalyticsImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/policies': {
      id: '/_sidebar/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof SidebarPoliciesImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/clusters/': {
      id: '/_sidebar/clusters/'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof SidebarClustersIndexImport
      parentRoute: typeof SidebarImport
    }
    '/_sidebar/clusters/$clusterId': {
      id: '/_sidebar/clusters/$clusterId'
      path: '/clusters/$clusterId'
      fullPath: '/clusters/$clusterId'
      preLoaderRoute: typeof SidebarClustersClusterIdImport
      parentRoute: typeof SidebarImport
    }
  }
}

// Create and export the route tree

interface SidebarRouteChildren {
  SidebarAnalyticsRoute: typeof SidebarAnalyticsRoute
  SidebarPoliciesRoute: typeof SidebarPoliciesRoute
  SidebarClustersIndexRoute: typeof SidebarClustersIndexRoute
  SidebarClustersClusterIdRoute: typeof SidebarClustersClusterIdRoute
}

const SidebarRouteChildren: SidebarRouteChildren = {
  SidebarAnalyticsRoute: SidebarAnalyticsRoute,
  SidebarPoliciesRoute: SidebarPoliciesRoute,
  SidebarClustersIndexRoute: SidebarClustersIndexRoute,
  SidebarClustersClusterIdRoute: SidebarClustersClusterIdRoute,
}

const SidebarRouteWithChildren = SidebarRoute._addFileChildren(
  SidebarRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof SidebarRouteWithChildren
  '/analytics': typeof SidebarAnalyticsRoute
  '/policies': typeof SidebarPoliciesRoute
  '/clusters': typeof SidebarClustersIndexRoute
  '/clusters/$clusterId': typeof SidebarClustersClusterIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof SidebarRouteWithChildren
  '/analytics': typeof SidebarAnalyticsRoute
  '/policies': typeof SidebarPoliciesRoute
  '/clusters': typeof SidebarClustersIndexRoute
  '/clusters/$clusterId': typeof SidebarClustersClusterIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteWithChildren
  '/_sidebar/analytics': typeof SidebarAnalyticsRoute
  '/_sidebar/policies': typeof SidebarPoliciesRoute
  '/_sidebar/clusters/': typeof SidebarClustersIndexRoute
  '/_sidebar/clusters/$clusterId': typeof SidebarClustersClusterIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/analytics'
    | '/policies'
    | '/clusters'
    | '/clusters/$clusterId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/analytics' | '/policies' | '/clusters' | '/clusters/$clusterId'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/analytics'
    | '/_sidebar/policies'
    | '/_sidebar/clusters/'
    | '/_sidebar/clusters/$clusterId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRoute: typeof SidebarRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRoute: SidebarRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */
